let num = 100;
if (num > 100) {
    console.log('Invalid(Input Marks value greater than total marks)')
} else if (num >= 33) {
    console.log('Result: Passed with ' + num + ' marks');
} else {
    console.log("Result: Failed");
}

// let time = 5.30;
// let name = 'Vivek..';
// if (time < 12 && time >= 5) {
//     console.log('Good Morning! ' + name);
// }
// else if (time < 17 && time >= 12) {
//     console.log('Good Afternoon ' + name)
// } else if (time < 20 && time >= 17){
//     console.log('Good Evening ' + name)
// } else {
//     console.log('Good Night ' + name)
// }

// end of code by VivekGupta